# Generated by Django 4.2.2 on 2024-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusName', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='campus',
            field=models.CharField(default='CUSAT', max_length=200),
        ),
    ]
