# Generated by Django 4.2.2 on 2024-06-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campus_usermodel_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
    ]
