# Generated by Django 4.2.2 on 2024-04-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_categoryid_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usermodel'),
        ),
    ]
