# Generated by Django 4.2.2 on 2024-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.usermodel'),
        ),
    ]
